### ISSUE TITLE
不好意思忘记 cc 你！！

### ISSUE THREAD

**Issue by Latias94** [Locietta/blog-lost-pieces#5]
你好，
        偶然间搜到您的周记：https://github.com/Locietta/blog-lost-pieces/blob/main/weekly/20230923.md 发现您尝试封 gfx 还用 xmake 感觉和我的用法差不多，又看到你提到有人提到直接拿了你的脚本做贡献，才发现这就是我干的事😵。当时本意是想提个 issue 让作者有空写一下，没想到作者直接让我提 pr，那时候我才接触 xmake，写脚本也不是很熟，赶着 xmake 新版本发布之际调了调就把您的脚本提交上去了，没有和你沟通过是我的过失，现在已经在 https://github.com/xmake-io/xmake/pull/4149 mr 中补充。

再次致歉！
猫冬

**Comment by Locietta** [comment]
哈哈，问题不大而且也过去好久了~
那个hlsl2spv是当时图省事不想调api就直接照着xmake的glsl2spv改的。后来发现正经写还是调dxc的api更好所以就没管这个脚本了，也没想着交到上游去。不过既然提交上去了也是件好事，万一谁就用上了呢x
